language: objective-c
osx_image: xcode7.3
script:
- xcodebuild clean build -workspace Examples/SKAsyncGLViewController/SKAsyncGLViewController.xcworkspace -scheme SKAsyncGLViewController -sdk iphonesimulator
