language: objective-c
osx_image: xcode7.3
script: 
- travis_wait 30 xcodebuild clean build -workspace Examples/SKThreadSafeReference/SKThreadSafeReference.xcworkspace -scheme SKThreadSafeReference -sdk iphonesimulator
