install: travis_wait 30 mvn install
language: objective-c
osx_image: xcode7.3
script: 
- xcodebuild clean build -workspace Examples/SKThreadSafeReference/SKThreadSafeReference.xcworkspace -scheme SKThreadSafeReference -sdk iphonesimulator
